# Generated by Django 5.2.2 on 2025-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='timer_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
